# Generated by Django 5.2 on 2025-05-28 20:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicaPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informacion_dueno', models.TextField(max_length=255)),
                ('direccion', models.CharField(max_length=100)),
                ('color_general', models.CharField(max_length=100)),
                ('superficie_terreno', models.IntegerField()),
                ('metros_cuadrados', models.IntegerField()),
                ('habitacion', models.IntegerField()),
                ('estacionamiento', models.IntegerField()),
                ('cocina', models.IntegerField()),
                ('sala', models.IntegerField()),
                ('pisos', models.IntegerField()),
                ('tipo_propiedad', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('terreno', 'Terreno')], default='casa', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('titulo_dominio', 'Título de dominio'), ('cert_dominio_vigente', 'Certificado de dominio vigente'), ('cert_hipotecas', 'Certificado de hipotecas y gravámenes'), ('recepcion_final', 'Recepción final'), ('cert_gastos_comunes', 'Certificado de gastos comunes'), ('otros', 'Otros')], max_length=50)),
                ('archivo', models.FileField(upload_to='documentos_propiedades/')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_propiedades/')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_tramite', models.CharField(max_length=255)),
                ('estipulacion_final', models.TextField()),
                ('estado_proceso_pago', models.CharField(choices=[('deposito-aceptado', 'Deposito-Aceptado'), ('deposito-rechazado', 'Deposito-Rechazado'), ('deposito-en-proceso', 'Deposito-En-Proceso')], max_length=50)),
                ('valor', models.DecimalField(decimal_places=0, max_digits=50)),
                ('estado_final_pago', models.CharField(choices=[('Finalizado', 'finalizado'), ('NO-Finalizado', 'no-finalizado')], default='NO-Pagado', max_length=50)),
                ('estado_error_tramite', models.CharField(choices=[('Sin-Errores!', 'sin-errores!'), ('No-Se-Pudo-Realizar', 'No-Se-Pudo-Realizar'), ('Se-Pudo-Finalizar-La-Tramitacion', 'se-pudo-finalizar-la-tramitacion'), ('Se-ReAbre-Tramitacion', 'se-reabre-tramitacion')], default='Sin-Errores!', max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Proceso_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('vender', 'Vender'), ('arriendo', 'Arriendo')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado_tramitacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('visibilidad', models.CharField(choices=[('visible', 'Visible'), ('oculto', 'Oculto')], default='visible', max_length=10)),
                ('activo', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComunicacionCorredor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.administrador')),
            ],
        ),
    ]
