# Generated by Django 5.2 on 2025-05-28 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
        ('cliente', '0001_initial'),
        ('corredor', '0001_initial'),
        ('dueno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicacioncorredor',
            name='corredor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corredor.corredor'),
        ),
        migrations.AddField(
            model_name='comunicacioncorredor',
            name='dueno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dueno.dueno'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.administrador'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='corredor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corredor.corredor'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='dueno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dueno.dueno'),
        ),
        migrations.AddField(
            model_name='proceso_pago',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
        migrations.AddField(
            model_name='proceso_pago',
            name='corredor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corredor.corredor'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.administrador'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='corredor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corredor.corredor'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='dueno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dueno.dueno'),
        ),
        migrations.AddField(
            model_name='proceso_pago',
            name='propiedad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='procesoPagoPropiedad', to='administrador.propiedad'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='propiedad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagoPropiedad', to='administrador.propiedad'),
        ),
        migrations.AddField(
            model_name='imagenpropiedad',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='administrador.propiedad'),
        ),
        migrations.AddField(
            model_name='documentopropiedad',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='administrador.propiedad'),
        ),
        migrations.AddField(
            model_name='comunicacioncorredor',
            name='propiedad_mensaje',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comunicacionCorredor', to='administrador.propiedad'),
        ),
        migrations.AddField(
            model_name='caracteristicapropiedad',
            name='propiedad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='administrador.propiedad'),
        ),
    ]
