# Generated by Django 5.2 on 2025-05-29 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_initial'),
        ('cliente', '0001_initial'),
        ('corredor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_campaña', models.CharField(choices=[('atraccion', 'Atracción'), ('interaccion', 'Interacción'), ('conversion', 'Conversión'), ('fidelizacion', 'Fidelización'), ('ninguna', 'Ninguna')], default='ninguna', max_length=20)),
                ('estado', models.CharField(choices=[('no_contactado', 'No contactado'), ('llamada', 'Llamada'), ('interesado', 'Interesado'), ('no_interesado', 'No interesado'), ('reunion', 'Reunión'), ('cierre', 'Cierre'), ('pendiente', 'Pendiente'), ('ninguna', 'Ninguna')], default='no_contactado', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_contacto', models.DateField(blank=True, null=True)),
                ('fecha_siguiente', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='cliente.cliente')),
                ('corredor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='corredor.corredor')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='administrador.propiedad')),
            ],
        ),
    ]
